In [31]:
import numpy as np
import pandas as pd
iris = pd.read_csv('Parkinsondisease.csv')
iris.head()

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0  phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1  phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2  phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3  phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4  phon_R01_S01_5      116.014       141.781       110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0           0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1           0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2           0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3           0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4           0.00011   0.00655   0.00908     0.01966       0.06425  ...   

   Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0      0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1      0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2      0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3      0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4      0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   

    spread2        D2       PPE  
0  0.266482  2.301442  0.284654  
1  0.335590  2.486855  0.368674  
2  0.311173  2.342259  0.332634  
3  0.334147  2.405554  0.368975  
4  0.234513  2.332180  0.410335  

[5 rows x 24 columns]

In [38]:
x = iris.drop(['status','name'],axis=1)
y = iris['status']

In [39]:
pd.DataFrame(x,columns=iris.columns[:-1])

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0     NaN      119.992       157.302        74.997         0.00784   
1     NaN      122.400       148.650       113.819         0.00968   
2     NaN      116.682       131.111       111.555         0.01050   
3     NaN      116.676       137.871       111.366         0.00997   
4     NaN      116.014       141.781       110.655         0.01284   
..    ...          ...           ...           ...             ...   
190   NaN      174.188       230.978        94.261         0.00459   
191   NaN      209.516       253.017        89.488         0.00564   
192   NaN      174.688       240.005        74.287         0.01360   
193   NaN      198.764       396.961        74.904         0.00740   
194   NaN      214.289       260.277        77.973         0.00567   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0             0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1             0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2             0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3             0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4             0.00011   0.00655   0.00908     0.01966       0.06425  ...   
..                ...       ...       ...         ...           ...  ...   
190           0.00003   0.00263   0.00259     0.00790       0.04087  ...   
191           0.00003   0.00331   0.00292     0.00994       0.02751  ...   
192           0.00008   0.00624   0.00564     0.01873       0.02308  ...   
193           0.00004   0.00370   0.00390     0.01109       0.02296  ...   
194           0.00003   0.00295   0.00317     0.00885       0.01884  ...   

     MDVP:APQ  Shimmer:DDA      NHR     HNR  status      RPDE       DFA  \
0     0.02971      0.06545  0.02211  21.033     NaN  0.414783  0.815285   
1     0.04368      0.09403  0.01929  19.085     NaN  0.458359  0.819521   
2     0.03590      0.08270  0.01309  20.651     NaN  0.429895  0.825288   
3     0.03772      0.08771  0.01353  20.644     NaN  0.434969  0.819235   
4     0.04465      0.10470  0.01767  19.649     NaN  0.417356  0.823484   
..        ...          ...      ...     ...     ...       ...       ...   
190   0.02745      0.07008  0.02764  19.517     NaN  0.448439  0.657899   
191   0.01879      0.04812  0.01810  19.147     NaN  0.431674  0.683244   
192   0.01667      0.03804  0.10715  17.883     NaN  0.407567  0.655683   
193   0.01588      0.03794  0.07223  19.020     NaN  0.451221  0.643956   
194   0.01373      0.03078  0.04398  21.209     NaN  0.462803  0.664357   

      spread1   spread2        D2  
0   -4.813031  0.266482  2.301442  
1   -4.075192  0.335590  2.486855  
2   -4.443179  0.311173  2.342259  
3   -4.117501  0.334147  2.405554  
4   -3.747787  0.234513  2.332180  
..        ...       ...       ...  
190 -6.538586  0.121952  2.657476  
191 -6.195325  0.129303  2.784312  
192 -6.787197  0.158453  2.679772  
193 -6.744577  0.207454  2.138608  
194 -5.724056  0.190667  2.555477  

[195 rows x 23 columns]

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

# svm


In [41]:
from sklearn import svm
clf = svm.SVC(kernel='linear',C=0.01)
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 6  4]
 [ 1 28]]
0.8717948717948718
              precision    recall  f1-score   support

           0       0.86      0.60      0.71        10
           1       0.88      0.97      0.92        29

    accuracy                           0.87        39
   macro avg       0.87      0.78      0.81        39
weighted avg       0.87      0.87      0.86        39



# RandomForest

In [42]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(n_estimators=10)
rf_clf.fit(x_train,y_train)
y_rf=rf_clf.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
print(confusion_matrix(y_test,y_rf))
print(accuracy_score(y_test,y_rf))
print(classification_report(y_test,y_rf))

[[10  0]
 [ 2 27]]
0.9487179487179487
              precision    recall  f1-score   support

           0       0.83      1.00      0.91        10
           1       1.00      0.93      0.96        29

    accuracy                           0.95        39
   macro avg       0.92      0.97      0.94        39
weighted avg       0.96      0.95      0.95        39



# GradientBoost

In [43]:
from sklearn.ensemble import GradientBoostingClassifier
grad_boost = GradientBoostingClassifier(learning_rate=0.1)
grad_boost.fit(x_train,y_train)
y_grad = grad_boost.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
print(confusion_matrix(y_test,y_grad))
print(accuracy_score(y_test,y_grad))
print(classification_report(y_test,y_grad))

[[ 9  1]
 [ 1 28]]
0.9487179487179487
              precision    recall  f1-score   support

           0       0.90      0.90      0.90        10
           1       0.97      0.97      0.97        29

    accuracy                           0.95        39
   macro avg       0.93      0.93      0.93        39
weighted avg       0.95      0.95      0.95        39



# Adaboost

In [44]:
from sklearn.ensemble import AdaBoostClassifier
ada_boost = AdaBoostClassifier()
ada_boost.fit(x_train,y_train)
y_ada = ada_boost.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
print(confusion_matrix(y_test,y_ada))
print(accuracy_score(y_test,y_ada))
print(classification_report(y_test,y_ada))

[[10  0]
 [ 4 25]]
0.8974358974358975
              precision    recall  f1-score   support

           0       0.71      1.00      0.83        10
           1       1.00      0.86      0.93        29

    accuracy                           0.90        39
   macro avg       0.86      0.93      0.88        39
weighted avg       0.93      0.90      0.90        39



# xgb


In [45]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [46]:
from xgboost import XGBClassifier
xgb_clf = XGBClassifier(learning_rate=1)
xgb_clf.fit(x_train,y_train)
y_xgb = xgb_clf.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
print(confusion_matrix(y_test,y_xgb))
print(accuracy_score(y_test,y_xgb))
print(classification_report(y_test,y_xgb))

[[10  0]
 [ 2 27]]
0.9487179487179487
              precision    recall  f1-score   support

           0       0.83      1.00      0.91        10
           1       1.00      0.93      0.96        29

    accuracy                           0.95        39
   macro avg       0.92      0.97      0.94        39
weighted avg       0.96      0.95      0.95        39



# catboost

In [48]:
pip install catboost

Note: you may need to restart the kernel to use updated packages.


In [52]:
from catboost import CatBoostClassifier
cat_clf = CatBoostClassifier()
cat_clf.fit(x_train,y_train)
y_pred_cat = cat_clf.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred_cat))
print(accuracy_score(y_test,y_pred_cat))
print(classification_report(y_test,y_pred_cat))

Learning rate set to 0.00466
0:	learn: 0.6874704	total: 4.65ms	remaining: 4.65s
1:	learn: 0.6836159	total: 7.58ms	remaining: 3.78s
2:	learn: 0.6798267	total: 9.83ms	remaining: 3.27s
3:	learn: 0.6759474	total: 13.2ms	remaining: 3.28s
4:	learn: 0.6714390	total: 16.3ms	remaining: 3.24s
5:	learn: 0.6673186	total: 19.3ms	remaining: 3.2s
6:	learn: 0.6633613	total: 22.5ms	remaining: 3.19s
7:	learn: 0.6578556	total: 24.9ms	remaining: 3.09s
8:	learn: 0.6540703	total: 27.6ms	remaining: 3.04s
9:	learn: 0.6494342	total: 29.7ms	remaining: 2.94s
10:	learn: 0.6447813	total: 31.6ms	remaining: 2.84s
11:	learn: 0.6402822	total: 33.7ms	remaining: 2.77s
12:	learn: 0.6355007	total: 35.8ms	remaining: 2.72s
13:	learn: 0.6315101	total: 38ms	remaining: 2.67s
14:	learn: 0.6281260	total: 39.9ms	remaining: 2.62s
15:	learn: 0.6236148	total: 42.1ms	remaining: 2.59s
16:	learn: 0.6190982	total: 44.2ms	remaining: 2.56s
17:	learn: 0.6162032	total: 46.2ms	remaining: 2.52s
18:	learn: 0.6114842	total: 48.2ms	remaining: 2.